rSystem/config/routes.rb
RSystem::Application.routes.draw do
  resources :news_parsers

  match "/news_parser" => 'news_parsers#create', via: :post, as: :create_parser
  root 'news_parsers#index'

  

end

rSystem/app/models/news_parser.rb
require 'nokogiri'
require 'open-uri'
require 'uri'

class NewsParser < ActiveRecord::Base
	attr_accessor :queries, :contents
	serialize :queries, Array
	serialize :contents, Hash
	RICH_CONTENT_KEY = "rca.1.1.20140325T124443Z.4617706c8eb8ca49.f55bbec26c11f882a82500daa69448a3e80dfef9"
	XML_KEY = "03.221067681:17248ebd10d4013eab1585f73ddbec5f"

	def add_query str
		@queries ||= []
		@queries << CGI.escape(str).gsub('%2A', '*').gsub('%7E', '~').gsub('%21', '!').gsub('%28', '(').gsub('%29', ')')

	end

	def run!
		group_count = 5
		in_group = 1
		groupby = "attr%3Dd.mode%3Ddeep.groups-on-page%3D#{group_count}.docs-in-group%3D#{in_group}"
		sortby = "rlv" #"tm.order%3Ddescending" 
		@contents ||= {}
		@queries.each_with_index do |query, index|
			url = "http://xmlsearch.yandex.ru/xmlsearch?user=kmi9-ya&key=#{XML_KEY}&query=#{query}&sortby=#{sortby}&filter=none&maxpassages=1&groupby=#{groupby}&l10n=ru"
			doc = Nokogiri::HTML(open_url(url, "Can't get data from Yandex XML. #{index}"))
			puts doc
			links = doc.css('yandexsearch response results group doc url').map{|l| l.content}
			puts "Links count: #{links.size}"
			links.each_with_index do |link, index|
				puts "#{index}. Processing... " + link
				unless @contents.has_key?(link)
					yandex_rich_url = "http://rca.yandex.com/?key=#{RICH_CONTENT_KEY}&url=#{URI.escape(link)}&content=full"
					doc = open_url(yandex_rich_url, "URL: #{link}")
					if (doc)
						doc = doc.readlines.join	
						rich_ret = JSON.parse(doc)
						@contents[link] = [rich_ret["title"] ? CGI.unescapeHTML(rich_ret["title"]) : "", rich_ret["content"] ? CGI.unescapeHTML(rich_ret["content"]) : ""]
					else
						puts "Can't download #{link}. -----------------"
						next
					end
				end
			end
		end
	end

private

	def open_url url, err_text = ""
		i = 0
		doc = nil
		while (i += 1 ) <= 2
			begin
				doc = open(url)
				break
			rescue Exception => e
				k = rand(10) + 5
				$stderr.puts "#{url} was not open. Sleep(#{k}). #{i}"
				$stderr.puts e.message 
				$stderr.puts err_text
				# ОБРАБОТАТЬ ПРАВИЛЬНО ОШИБКИ
				sleep(k)
			end
		end
		return nil if i == 10
		return doc
	end

end

rSystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rSystem/app/controllers/news_parsers_controller.rb
class NewsParsersController < ApplicationController
  before_action :set_news_parser, only: [:show, :destroy]

  # GET /news_parsers
  # GET /news_parsers.json
  def index
  end

  # GET /news_parsers/1
  # GET /news_parsers/1.json
  def show
  end

  # POST /news_parsers
  # POST /news_parsers.json
  def create
    # @news_parser = NewsParser.new([1,2,3], {1 => 3})
    # @news_parser.save
    @news_parser = NewsParser.new
    params[:query].each_value do |value|
      unless value.empty?
        @news_parser.add_query value
      end
    end
    @news_parser.run!
    render 'show'
    # respond_to do |format|
    #   if @news_parser.save
    #     format.html { redirect_to @news_parser}
    #     format.json { render action: 'show', status: :created, location: @news_parser }
    #   else
    #     format.html { render action: 'index' }
    #     format.json { render json: @news_parser.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /news_parsers/1
  # PATCH/PUT /news_parsers/1.json
  def update
    respond_to do |format|
      if @news_parser.update(news_parser_params)
        format.html { redirect_to @news_parser, notice: 'News parser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news_parser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_parsers/1
  # DELETE /news_parsers/1.json
  def destroy
    @news_parser.destroy
    respond_to do |format|
      format.html { redirect_to news_parsers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_parser
      @news_parser = NewsParser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_parser_params
      params.require(:news_parser).permit(:contents, :queries)
    end

end

rSystem/app/helpers/application_helper.rb
module ApplicationHelper
end

rSystem/app/helpers/news_parsers_helper.rb
module NewsParsersHelper
end

rSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="top">
	<h1>Система информационного реагирования на ЧС</h1>
	<div style="display: inline-block;">
		<%= form_tag({controller: "news_parsers", action: "create"}, method: "post") do %>
			<%= text_field_tag 'query[1]' %>
			<%= text_field_tag 'query[2]' %>
			<%= text_field_tag 'query[3]' %>
			<%= submit_tag "Старт" %>
		<% end %>
	</div>		
	<div style="display: inline-block; float: right">
		<%= link_to "Правила составления запросов в Yandex.", "http://help.yandex.ru/search/query-language/crib-sheet.xml", target: "_blank" %>
	</div>		
</div>

<hr>

<%= yield %>

</body>
</html>

rSystem/app/views/news_parsers/_form.html.erb
<%= form_for(@news_parser) do |f| %>
  <% if @news_parser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_parser.errors.count, "error") %> prohibited this news_parser from being saved:</h2>

      <ul>
      <% @news_parser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rSystem/app/views/news_parsers/edit.html.erb
<h1>Editing news_parser</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_parser %> |
<%= link_to 'Back', news_parsers_path %>

rSystem/app/views/news_parsers/index.html.erb
Введите запрос в форме выше. 

rSystem/app/views/news_parsers/new.html.erb
<h1>New news_parser</h1>

<%= render 'form' %>

<%= link_to 'Back', news_parsers_path %>

rSystem/app/views/news_parsers/show.html.erb
<p id="notice"><%= notice %></p>
<% i = 0 %> 
<% @news_parser.contents.each_key do |link| %>
	<p> <%= link_to link, "#anc#{i += 1}" %> </p>
<% end %>

<% i = 0 %> 
<% @news_parser.contents.each do |link, content| %>
	<div class="article">
		<p><a name="<%= "anc#{i += 1}" %>"></a><b> <%= content[0] %> </b> </p>
		<p> <%= link_to link, link %> </p>
		<p> <%= content[1] %> </p>
	</div>
<% end %>